package com.example.retrofitdemo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.retrofitdemo.Db_user;

import com.example.retrofitdemo.Db_userDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig db_userDaoConfig;

    private final Db_userDao db_userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        db_userDaoConfig = daoConfigMap.get(Db_userDao.class).clone();
        db_userDaoConfig.initIdentityScope(type);

        db_userDao = new Db_userDao(db_userDaoConfig, this);

        registerDao(Db_user.class, db_userDao);
    }
    
    public void clear() {
        db_userDaoConfig.getIdentityScope().clear();
    }

    public Db_userDao getDb_userDao() {
        return db_userDao;
    }

}
